### ISSUE TITLE
Sounds are missing 

### ISSUE THREAD

**Issue by henne90gen** [henne90gen/RacingToHell#1]
We need music and sound effects.

**Comment by aannleax** [comment]
Übernimmst du das?

**Comment by henne90gen** [comment]
Das war mehr so ein test. Wir können das gern zusammen machen.

**Comment by henne90gen** [comment]
Modestep - Game Over als GameOverScreen sound

**Comment by henne90gen** [comment]
Shot, motor and other sound effects maybe?

**Comment by henne90gen** [comment]
Not planning on adding any more sounds
