### ISSUE TITLE
Make AboutScreen

### ISSUE THREAD

**Issue by henne90gen** [henne90gen/RacingToHell#31]
Show who made the game, basicly credits

**Comment by henne90gen** [comment]
Basic layout is done might need some tweaking though. Leaving it open for now

**Comment by henne90gen** [comment]
"Level up sound effects" by Bart Kelsey. Commissioned by Will Corwin for OpenGameArt.org (http://opengameart.org)

**Comment by henne90gen** [comment]
KsTBeats

**Comment by aannleax** [comment]
Cartextures: http://opengameart.org/content/free-top-down-car-sprites-by-unlucky-studio

**Comment by henne90gen** [comment]
Grauer Lexus: https://lexusenthusiast.com/2013/11/06/lexus-bmw-working-together-on-a-hybrid-supercar/
Needs to be contacted first

**Comment by henne90gen** [comment]
Weißer Audi: http://fyidesigndept.com/wp-content/uploads/2009/06/r8-v10-52-fsi-quattro-2010-top-down-view_w800-713377.jpg
Needs to be contacted first
